### ISSUE TITLE
Question about the aaer dataset

### ISSUE THREAD

**Issue by josipsajrih** [JarFraud/FraudDetection#1]
Hi,

nice to meet you, your work is quite interesting. My college and me are currently working on our idea for a fraud model. We were wondering if it is possible to ask you for a favor and that is to upload the AAER raw data set so that we can preform EDA on it so that we can decide to go further with the model development.

Thank you in advance.

Šajrih Josip M.A.

**Comment by popeye007** [comment]
Hi Šajrih,

We cannot upload the raw AAER dataset, but you can find the information of AAER dataset here: https://sites.google.com/usc.edu/aaerdataset/home

Thanks.

**Comment by JarFraud** [comment]
Hi Šajrih,

We cannot upload the raw AAER dataset, but you can find the information of AAER dataset here: https://sites.google.com/usc.edu/aaerdataset/home

Thanks.
