### ISSUE TITLE
WRSD query to get accounting variables + new?

### ISSUE THREAD

**Issue by EdwardRaff** [JarFraud/FraudDetection#4]
Hi, I'm trying to compare with Benish M-Score and others that require some additional variables. I'm new to WRDS & compustat though. Could you share the query to get the raw data so that I can add other variables to it?

**Comment by Victoria123-hub** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我暂时不在，无法亲自回复您的邮件。我将尽快给您回复。

**Comment by JarFraud** [comment]
You could refer to the WRDS documentation here: https://wrds-www.wharton.upenn.edu/pages/support/getting-started/wrds-web-queries/

**Comment by EdwardRaff** [comment]
I am already referring to the WRDS documentation, but it has many different databases and is quite involved. If you can share the database and table (ideally, the whole SQL query) you used that would be a huge help in moving through this faster.
